name: Publish Image Using latest

on:
  push:
    branches:
      - main

jobs:
  publish-nextflow:
    name: Publish Nextflow Image latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/nextflow
          location: nextflow
          dockerfile: nextflow/Dockerfile
          tag_format: "latest"
